use hadobo;

INSERT INTO STUDENT VALUES(1, 'ola', 23, 'M');
INSERT INTO STUDENT VALUES(2, 'Gift', 23, 'F');
INSERT INTO STUDENT VALUES(3, 'Yanis', 23, 'M');
INSERT INTO STUDENT VALUES(4, 'Bekky', 23, 'F');
INSERT INTO COURSE VALUES(5, 'Java', 'Chibuzo', 1);
INSERT INTO COURSE VALUES(1, 'Python', 'sikiru', 32);
INSERT INTO COURSE VALUES(2, 'JavaScript', 'Chinedu', 31);
INSERT INTO COURSE VALUES(3, 'GO LANG', 'Mr Femi', 21);
INSERT INTO GRADE VALUES(2, 22, 70);
INSERT INTO GRADE VALUES(3,33,60);
INSERT INTO GRADE VALUES(1,22,80);
